services:
  ais-catcher:
    command: -C /config/config.json
    container_name: ais-catcher
    ports:
      - 8100:8100
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - ./ais-catcher/config:/config
    image: ghcr.io/jvde-github/ais-catcher:latest
    restart: always

  aisdispatcher:
    build:
      context: ./aisdispatcher
      dockerfile: Dockerfile
    image: aisdispatcher:latest
    container_name: aisdispatcher
    privileged: true
    network_mode: host
    restart: always

  aiscot:
    build:
      context: ./aiscot
      dockerfile: Dockerfile
    image: aiscot:latest
    container_name: aiscot
    privileged: true
    network_mode: host
    restart: always
